login:
    pattern:   /login
    defaults:  { _controller: NZZMyTownBundle:Security:login }
login_check:
    pattern:   /login_check
logout:
    pattern:   /logout


nzz_my_town_homepage:
    pattern:  /{projectShortname}/{lang}
    defaults: { _controller: NZZMyTownBundle:Default:index }
    requirements:
        lang: '\w{2}'
        projectShortname: '[^/]*'
        _method: GET


nzz_my_town_api_save:
    pattern:  /{projectShortname}/{lang}
    defaults: { _controller: NZZMyTownBundle:Api:save }
    requirements:
        lang: '\w{2}'
        projectShortname: '[^/]*'
        _method: POST

nzz_my_town_api_get_all:
    pattern:  /{project}/getAll
    defaults: { _controller: NZZMyTownBundle:Api:getAll }

nzz_my_town_api_publish_item:
    pattern:  /{project}/{itemId}
    defaults: { _controller: NZZMyTownBundle:Api:publish }

nzz_my_town_api_remove_item:
    pattern:  /{project}/{itemId}
    defaults: { _controller: NZZMyTownBundle:Api:remove }


nzz_my_town_admin_dashboard:
    pattern: /admin/
    defaults: { _controller: NZZMyTownBundle:Admin:index }

nzz_my_town_admin_add_project:
    pattern: /admin/add
    defaults: { _controller: NZZMyTownBundle:Admin:add }

nzz_my_town_admin_add_project:
    pattern: /admin/edit/{projectId}
    defaults: { _controller: NZZMyTownBundle:Admin:edit }