NZZAdminMyTownBundle_admin_nzz_admin_my_town_bundle_logo:
    resource: "@NZZAdminMyTownBundle/Controller/Logo/"
    type:     admingenerator
    prefix:   /a2/logo/

NZZAdminMyTownBundle_admin_nzz_admin_my_town_bundle_point:
    resource: "@NZZAdminMyTownBundle/Controller/Point/"
    type:     admingenerator
    prefix:   /a2/point/
#Dashboard
_welcome:
    pattern: /a2
    defaults: { _controller: NZZAdminMyTownBundle:Dashboard:index }

NZZAdminMyTownBundle_admin_nzz_admin_my_town_bundle_project:
    resource: "@NZZAdminMyTownBundle/Controller/Project/"
    type:     admingenerator
    prefix:   /a2/project/

vfe_my_town:
    resource: "@NZZMyTownBundle/Resources/config/routing.yml"
    prefix:   /

