vfe_my_town_homepage:
    pattern:  /{project}/{lang}/{zoom}
    defaults: { _controller: VFEMyTownBundle:Default:index }


vfe_my_town_api_save:
    pattern:  /{project}/save
    defaults: { _controller: VFEMyTownBundle:Api:save }
