generator: admingenerator.generator.propel
params:
    model: NZZ\MyTownBundle\Model\Point
    namespace_prefix: NZZ
    entity_manager: ~
    concurrency_lock: ~
    bundle_name: AdminMyTownBundle
    pk_requirement: ~
    fields: ~
    object_actions:
        delete: ~
    batch_actions:
        delete: ~
builders:
    list:
        params:
            title: List for AdminMyTownBundle
            display: ~
            actions:
                new: ~
            object_actions:
                edit: ~
                delete: ~
    filters:
        params:
            display: ~
    new:
        params:
            title: New object for AdminMyTownBundle
            display: ~
            actions:
                save: ~
                list: ~
    edit:
        params:
            title: "You're editing user's info"
            display: ~
            actions:
                save: ~
                list: ~
    show:
        params:
            title: "Project's comments"
            display: ~
            actions:
                list: ~
                new: ~
    actions:
        params:
            object_actions:
                delete: ~
            batch_actions:
                delete: ~
